[package]
name = "nostr-wallet-connect-lnd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
home = "0.5.12"
bitcoin = { version = "0.32.102", features = ["rand", "rand-std"] }
bitcoin-payment-instructions = "0.7.0"
lightning-invoice = { version = "0.34.1", features = ["serde", "std"] }
nostr = { version = "0.44.4", features = ["nip44", "nip47"] }
nostr-sdk = { version = "0.44.1", features = ["nip47"] }
tonic_openssl_lnd = { package = "lnd_grpc_rust", version = "2.16.0" }
tonic = "0.14.6"
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
hex = "0.4.3"
log = "0.4.33"
pretty_env_logger = "0.5.0"
